package resort;

import java.awt.Point;
import javax.swing.plaf.basic.BasicInternalFrameUI;

public class Homepage extends javax.swing.JInternalFrame {

    public Homepage() 
    {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI ui = (BasicInternalFrameUI)this.getUI();
        ui.setNorthPane(null); 
        scroll();
    }
    
    public void scroll() 
    {
        jScrollPane1.setWheelScrollingEnabled(false);
        jScrollPane1.getVerticalScrollBar().setUnitIncrement(30);

        jPanel1.addMouseWheelListener((java.awt.event.MouseWheelEvent evt) -> 
        {
            Point scroll = jScrollPane1.getViewport().getViewPosition();
            int dy = -evt.getWheelRotation() * -30;
            int maxScroll = jScrollPane1.getVerticalScrollBar().getMaximum() - jScrollPane1.getVerticalScrollBar().getModel().getExtent();
            if (scroll.y + dy < 0) { // if scrolling would go beyond the top of the panel
                dy = -scroll.y; // adjust dy to only scroll to the top
            } else if (scroll.y + dy > maxScroll) { // if scrolling would go beyond the bottom of the panel
                dy = maxScroll - scroll.y; // adjust dy to only scroll to the bottom
            }
            scroll.y += dy;
            jScrollPane1.getViewport().setViewPosition(scroll);
        });
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setBorder(null);
        setMaximumSize(new java.awt.Dimension(1280, 580));
        setMinimumSize(new java.awt.Dimension(1280, 580));
        setPreferredSize(new java.awt.Dimension(1280, 580));

        jScrollPane1.setBorder(null);
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane1.setMaximumSize(new java.awt.Dimension(1280, 580));
        jScrollPane1.setMinimumSize(new java.awt.Dimension(1280, 580));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(1280, 1160));

        jPanel1.setMaximumSize(new java.awt.Dimension(1280, 1740));
        jPanel1.setMinimumSize(new java.awt.Dimension(1280, 1740));
        jPanel1.setPreferredSize(new java.awt.Dimension(1280, 1740));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/pool.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 580));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/wide pool.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 580, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/bac.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 1160, -1, -1));

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 580, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
